name: 'Bitrise Trigger'
description: 'Triggers bitrise builds if path has changed files'
author: 'DriveTribe'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the bitrise trigger configurations'
    default: '.github/bitrise-triggers.yml'
  bitrise-token:
    description: 'Authentication token for bitrise api https://devcenter.bitrise.io/api/authentication/'
  bitrise-org-slug:
    description: 'Every organization has its own specific URL on Bitrise https://devcenter.bitrise.io/team-management/organizations/org-url/'
runs:
  using: 'node12'
  main: 'dist/index.js'
