name: 'Bitrise Trigger'
description: 'Triggers bitrise builds if path has changed files'
author: 'DriveTribe'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the bitrise trigger configurations'
    default: '.github/bitrise-triggers.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
